os: linux
language: shell

services:
- docker

addons:
  apt:
    packages:
    - docker-ce

  matrix:
  - ARCH=amd64 GOARCH=amd64 GOARM=6 QQEMU_ARCH=x86_64 TAG=amd64
  - ARCH=armhf GOARCH=arm   GOARM=6 QEMU_ARCH=arm     TAG=arm
  - ARCH=arm64 GOARCH=arm64 GOARM=6 QEMU_ARCH=arm64   TAG=arm64

before_install:
- mkdir -p ~/.docker/cli-plugins
- echo '{ "experimental":"enabled" }' > ~/.docker/config.json
- curl -L -o ~/.docker/cli-plugins/docker-buildx https://github.com/docker/buildx/releases/download/v0.5.1/buildx-v0.5.1.linux-amd64
- chmod +x ~/.docker/cli-plugins/docker-buildx
- curl -L https://goss.rocks/install | sudo sh

script:
- docker version
- docker buildx version
- docker build -t visibilityspots/cloudflared:$TAG --build-arg ARCH="$ARCH" --build-arg
  GOARCH="$GOARCH" --build-arg GOARM="$GOARM" ./
- dgoss run --name cloudflared -ti visibilityspots/cloudflared:$TAG
- echo "$DOCKER_PASSWORD" | docker login --username visibilityspots --password-stdin
#- docker push visibilityspots/cloudflared:$TAG

env:
  global:
    secure: nTT0E7Og68rCyPWKKf/J4208z5R/GHqPKXq7d5/MlikabiFJSttO0Qz1sMGu8qSAg3s1QdZrzB0gyspdIqIDTCtVYjJCxNx33+Uvmll2qd4iD0zAvlIQC1aPu2oC38c4tmyc9YZmNHeqSRiAmOPGm4LAL0weh+4hRshm+u78mkxfT7wHRBwIp7INBHoYz7D67omnztEBkvosrj39Zv1Ph/fHafNle6xUVaUGjialjjnJEfTuvmu0XDGZCm28cjudTMlWGJXcygn7dmPdT9S8LRtOPy6No2Xjo3t8B4gRsgo3pSAYcWEBZI+kst5MjVqE9qtZ47KA0jIayBTV6Gz2eKXM+iyms6TVRrT5xN8axB5f6KuwfiZm3btRj9SXtMLIJ/WhqYN+AF0qDYG1FaPGFP9BUXaTS+BkNjfAuDVsgQwx1oEJoQS+oEA89k6FU7ZmgJRq+oZPrmvrW+taRhM6NY2vCwiwRttBDWFTJTB4SdJ8qVkHbF1o1/79Wzr5bTwvI+HbbPibxfGLF2eeuSoju+7EDGV5E4ZeW/4BpUb+f6I7QpvrW/On3iiMe270z/j2uDWQlLUldS89ngCwWEIS8gIOM6ADx8YcuMSTSCLIR55CNKXxQMy4H0HDLeN3Y7/y6sRxmXv5iI0ESwYrh71g+waIFyHJUXCBuuZ72X+usoY=
