dist: focal
os: linux
language: shell

addons:
  apt:
    packages:
      - qemu-user-static

before_install:
- qemu-aarch64-static --version
- update-binfmts --version
- echo '{"experimental":"enabled"}' | sudo tee /etc/docker/daemon.json
- mkdir -p $HOME/.docker/
- echo '{ "experimental":"enabled" }' | sudo tee $HOME/.docker/config.json
- export DOCKER_CLI_EXPERIMENTAL=enabled
- docker info
- DOCKER_APT_REPO="https://download.docker.com/linux/ubuntu"
- curl -fsSL "${DOCKER_APT_REPO}/gpg" | sudo apt-key add -
- OS="$(lsb_release -cs)"
- sudo add-apt-repository "deb [arch=amd64] $DOCKER_APT_REPO $OS stable"
- sudo apt-get update
- sudo apt-get -y install docker-ce
#- curl -L -o ~/.docker/cli-plugins/docker-buildx https://github.com/docker/buildx/releases/download/v0.5.1/buildx-v0.5.1.linux-amd64
#- chmod +x ~/.docker/cli-plugins/docker-buildx
- echo "$DOCKER_PASSWORD" | docker login --username visibilityspots --password-stdin
- docker info

install:
- echo $DOCKER_CLI_EXPERIMENTAL
- docker info
- docker buildx
#- docker buildx create --use

script:
- docker info
#- docker buildx version
#- docker buildx build --platform linux/amd64,linux/arm,linux/arm64 --tag visibilityspots/cloudflared:latest . --push

env:
  global:
    secure: nTT0E7Og68rCyPWKKf/J4208z5R/GHqPKXq7d5/MlikabiFJSttO0Qz1sMGu8qSAg3s1QdZrzB0gyspdIqIDTCtVYjJCxNx33+Uvmll2qd4iD0zAvlIQC1aPu2oC38c4tmyc9YZmNHeqSRiAmOPGm4LAL0weh+4hRshm+u78mkxfT7wHRBwIp7INBHoYz7D67omnztEBkvosrj39Zv1Ph/fHafNle6xUVaUGjialjjnJEfTuvmu0XDGZCm28cjudTMlWGJXcygn7dmPdT9S8LRtOPy6No2Xjo3t8B4gRsgo3pSAYcWEBZI+kst5MjVqE9qtZ47KA0jIayBTV6Gz2eKXM+iyms6TVRrT5xN8axB5f6KuwfiZm3btRj9SXtMLIJ/WhqYN+AF0qDYG1FaPGFP9BUXaTS+BkNjfAuDVsgQwx1oEJoQS+oEA89k6FU7ZmgJRq+oZPrmvrW+taRhM6NY2vCwiwRttBDWFTJTB4SdJ8qVkHbF1o1/79Wzr5bTwvI+HbbPibxfGLF2eeuSoju+7EDGV5E4ZeW/4BpUb+f6I7QpvrW/On3iiMe270z/j2uDWQlLUldS89ngCwWEIS8gIOM6ADx8YcuMSTSCLIR55CNKXxQMy4H0HDLeN3Y7/y6sRxmXv5iI0ESwYrh71g+waIFyHJUXCBuuZ72X+usoY=
