---
version: "2"

services:
  cloudflared:
    image: Knight1/cloudflared
    container_name: cloudflared
    ports:
      - "54:53/tcp"
      - "54:53/udp"
    environment:
        TZ: ${TIMEZONE}
        PORT: 54
        ADDRESS: 0.0.0.0
    restart: always
    networks:
      cloudflared_net:
        ipv4_address: 10.0.0.2

networks:
  cloudflared_net:
    driver: bridge
    ipam:
     config:
       - subnet: 10.0.0.0/29
