name: docker-hub-description

on:
  push:
    branches: [ "master" ]

jobs:
  update:

    permissions:
      contents: read
      security-events: write

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Update docker hub description
        uses: peter-evans/dockerhub-description@v4
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
          repository: peterevans/dockerhub-description
          short-description: ${{ github.event.repository.description }}
